package flowgraph

import (
	"context"
	"io"
	"log/slog"
	"testing"

	"github.com/stretchr/testify/assert"
)

// TestWithLogger tests WithLogger option.
func TestWithLogger(t *testing.T) {
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	ctx := NewContext(context.Background(), WithLogger(logger))

	assert.Same(t, logger, ctx.Logger())
}

// TestWithCheckpointer tests WithCheckpointer option.
func TestWithCheckpointer(t *testing.T) {
	// Since CheckpointStore is an interface with no methods yet,
	// we can't really test this meaningfully, but we verify the option works
	ctx := NewContext(context.Background(), WithCheckpointer(nil))
	assert.Nil(t, ctx.Checkpointer())
}

// TestContext_RunIDAutoGenerated tests auto-generated run ID.
func TestContext_RunIDAutoGenerated(t *testing.T) {
	ctx1 := NewContext(context.Background())
	ctx2 := NewContext(context.Background())

	// Both should have non-empty, unique run IDs
	assert.NotEmpty(t, ctx1.RunID())
	assert.NotEmpty(t, ctx2.RunID())
	assert.NotEqual(t, ctx1.RunID(), ctx2.RunID())
}

// TestContext_DefaultAttempt tests default attempt is 1.
func TestContext_DefaultAttempt(t *testing.T) {
	ctx := NewContext(context.Background())
	assert.Equal(t, 1, ctx.Attempt())
}
